version: "3.9"

services:

  db:
    container_name: my_pg_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "5000"

  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./cert:/cert
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


